name: Test

on:
  push:
    paths:
      - ".github/**"
      - "agent/**"
      - "game/**"
      - "tests/**"
      - "utils/**"
      - "*.py"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Install & setting poetry
        run: |
          pip install -r requirements.txt

      - name: Test with pytest
        run: pytest tests